# Generated by Django 4.1.1 on 2022-10-10 08:20

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_alter_user_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="lat",
        ),
        migrations.RemoveField(
            model_name="user",
            name="lon",
        ),
        migrations.AlterField(
            model_name="user",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[django.core.validators.MinLengthValidator(10)],
            ),
        ),
        migrations.DeleteModel(
            name="Point",
        ),
    ]
